### ISSUE TITLE
Connect Authentication from Frontend to Backend

### ISSUE THREAD

**Issue by Howl1935** [hack4impact-calpoly/veggie-rescue#54]
**Task:**
Use backend routes for authentication and connect to LoginPage as well as AdminLogin.

**Steps:**
1.	Add Redux-Toolkit (For state management), and Toast (For notifications) to frontend.
2.	Create /src/app/store.tsx for store
3.	Create /src/features/driverAuth with driverAuthSlice.tsx
4.	Create a slice called authSlice, upon entering pin or credentials admin pass given info to backend and validate.  If invalid use toast to inform user with notification.  If valid, return user token and store in localStorage.  We will use this token to access protected routes in the backend.

**Success Metrics**
- [ ] Driver can enter pin and upon completion see a 'Invalid Credentials' notification, or 'Welcome {name}'
- [ ] Admin can enter pin and upon completion see a 'Invalid Credentials' notification, or 'Welcome {name}'
- [ ] For driver; If access is granted page should navigate to vehicles page
- [ ] For admin; If access is granted page should navigate to admin home page.
- [ ] In both cases, returned data from API call should be stored into local storage to prevent having to login constantly

**Comment by sophsuan** [comment]
can merge after merge conflicts get resolved (make sure changes in main aren't lost and overall application still functions with no errors, especially in package.json files)
